### ISSUE TITLE
exception thrown when map is loaded

### ISSUE THREAD

**Issue by wzbfyb** [abmantis/ozw-network-visualization-card#1]
Hi,

I downloaded the card js yesterday and manually put it into the config/www folder of my HA Install (0.114.2).
unfortunately it throws this error:

`home-assistant   | 2020-08-20 09:29:57 ERROR (MainThread) [frontend.js.latest.202008110] http://smarthomeserver:8123/local/ozw-network-visualization-card.js:6:0 SyntaxError: expected expression, got '<'
`

**Comment by abmantis** [comment]
@wzbfyb Can you show me a print of the file on your server? I suspect you may have copied some extra chars or something like that.

**Comment by wzbfyb** [comment]
here it is!

thanks

**Comment by abmantis** [comment]
@wzbfyb sorry, but the image is missing

**Comment by wzbfyb** [comment]
strange, lets try again
![Bildschirmfoto 2020-08-20 um 19 05 07 PM](https://user-images.githubusercontent.com/57131473/90826595-05512100-e33b-11ea-9b3f-136ca23c5db7.png)
![Bildschirmfoto 2020-08-20 um 19 05 14 PM](https://user-images.githubusercontent.com/57131473/90826607-097d3e80-e33b-11ea-8af6-496b381cb40e.png)
![Bildschirmfoto 2020-08-20 um 19 05 18 PM](https://user-images.githubusercontent.com/57131473/90826612-0aae6b80-e33b-11ea-9b62-b68660746720.png)

**Comment by abmantis** [comment]
It looks fine. Have you had the wrong file there before? If so, HA may have cached it. You can try rebooting HA and see if it fixes it. Also, do CTRL+F5 to refresh.

**Comment by wzbfyb** [comment]
thanks. rebooting the docker container and clearing the cache helped. thanks a lot!

**Comment by abmantis** [comment]
Great!
