### ISSUE TITLE
Card does not load

### ISSUE THREAD

**Issue by oldnasser** [abmantis/ozw-network-visualization-card#2]
error on line 155 Setter withouth getter

**Comment by abmantis** [comment]
Try the following: https://github.com/abmantis/ozw-network-visualization-card/issues/1#issuecomment-677916186
If it does not help, show me a screenshot of the lines surrounding 155.
Also, please give me the full error and where you are seeing it.

EDIT: isn't that a eslint error?

**Comment by oldnasser** [comment]
Cntrl+f5 did it. Thanks Sent from Mail for Windows 10 From: Abílio CostaSent: Sunday, August 23, 2020 8:13 PMTo: abmantis/ozw-network-visualization-cardCc: oldnasser; AuthorSubject: Re: [abmantis/ozw-network-visualization-card] Card does not load (#2) Try the following: #1 (comment)If it does not help, show me a screenshot of the lines surrounding 155.Also, please give me the full error and where you are seeing it.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
