### ISSUE TITLE
Empty card for Zwave2MQTT and ZwaveJS2MQTT

### ISSUE THREAD

**Issue by raetha** [abmantis/ozw-network-visualization-card#6]
Hi!

I saw an existing entry for ZJS2M support, but think my issue is a little different than just support for the newer project. I've used OZW, Z2M and ZJS2M. Only OZW worked flawlessly with the card, however that integration leaves a lot to be desired at the moment. With Z2M and ZJS2M the card always appears empty. You get the search box at the top, but no map.

My best guess is that this card is dependent on specific options or configuration on the Z2M side being set so that data flowing into MQTT looks a certain way.

Is there any documentation or guidance as to what MQTT settings on the Z2M side are needed? I'm guessing things like the name of the topic root, or what data is contained in each topic.

Would love to just see some guidance as to what this is expecting from Z2M in order to display the map.

Thanks, and great work, the card looked very nice during my brief foray into OZW land, and would love to see it working again.
-eli

**Comment by abmantis** [comment]
Hey. Yes, I have some hardcoded stuff at the moment, unfortunately.
On the Mqtt settings of Z2M, try setting:

- Name: HA
- Prefix: z2m

I think those should be enough to get the card to work.
